package entities;

public class trajet {

    private int id_trajet;  // Auto-generated by the database
    private int id_voyage;  // Foreign key to the voyage table
    private String type_transport;  // e.g., taxi, bus, airplane
    private String compagnie;  // e.g., Air France, Delta, Uber, etc.
    private double cout;  // Cost of the trip
    private String ville_depart;  // Departure city
    private String ville_arrivee;  // Arrival city

    // Default constructor
    public trajet() {
    }

    // Full constructor with id_trajet (which will be auto-generated in the database)
    public trajet(int id_voyage, String type_transport, String compagnie, double cout, String ville_depart, String ville_arrivee) {
        this.id_voyage = id_voyage;
        setType_transport(type_transport);
        setCompagnie(compagnie);
        this.cout = cout;
        setVille_depart(ville_depart);
        setVille_arrivee(ville_arrivee);
    }

    // Constructor without auto-generated id_trajet
    public trajet(int id_trajet, int id_voyage, String type_transport, String compagnie, double cout, String ville_depart, String ville_arrivee) {
        this.id_trajet = id_trajet;
        this.id_voyage = id_voyage;
        setType_transport(type_transport);
        setCompagnie(compagnie);
        this.cout = cout;
        setVille_depart(ville_depart);
        setVille_arrivee(ville_arrivee);
    }

    public int getId_trajet() {
        return id_trajet;
    }

    public void setId_trajet(int id_trajet) {
        this.id_trajet = id_trajet;
    }

    public int getId_voyage() {
        return id_voyage;
    }

    public void setId_voyage(int id_voyage) {
        this.id_voyage = id_voyage;
    }

    public String getType_transport() {
        return type_transport;
    }

    public void setType_transport(String type_transport) {
        this.type_transport = type_transport;
    }

    public double getCout() {
        return cout;
    }

    public void setCout(double cout) {
        this.cout = cout;
    }

    public String getCompagnie() {
        return compagnie;
    }

    public void setCompagnie(String compagnie) {
        this.compagnie = compagnie;
    }

    public String getVille_depart() {
        return ville_depart;
    }

    public void setVille_depart(String ville_depart) {
        this.ville_depart = ville_depart;
    }

    public String getVille_arrivee() {
        return ville_arrivee;
    }

    public void setVille_arrivee(String ville_arrivee) {
        this.ville_arrivee = ville_arrivee;
    }

    @Override
    public String toString() {
        return "Trajet{" +
                "id_trajet=" + id_trajet +
                ", id_voyage=" + id_voyage +
                ", type_transport='" + type_transport + '\'' +
                ", compagnie='" + compagnie + '\'' +
                ", cout=" + cout +
                ", ville_depart='" + ville_depart + '\'' +
                ", ville_arrivee='" + ville_arrivee + '\'' +
                '}';
    }
}
